version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://badisjl99:123951Ba008@mongo:27017/mydb?authSource=mydb
    depends_on:
      - mongo
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app_network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: badisjl99
      MONGO_INITDB_ROOT_PASSWORD: 123951Ba008

networks:
  app_network:
    driver: bridge

volumes:
  mongo-data: