version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - frontend-build:/var/www/react-build
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8082"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://badisjl99:123951Ba008@mongo:27017/mydb?authSource=admin
      - JWT_SECRET=BFEec8JKk:FZz3f0F812f.0051293f
      - COOKIE_NAME=token
    depends_on:
      - mongo
    networks:
      - app_network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend-build:/usr/share/nginx/html
    networks:
      - app_network
    restart: always

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: badisjl99
      MONGO_INITDB_ROOT_PASSWORD: 123951Ba008
networks:
  app_network:
    driver: bridge
volumes:
  mongo-data:
  frontend-build: