version: "3.8"

services:
  nginx:
    # This service builds the frontend and serves it with Nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      # Mounts the updated nginx.conf into the container
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # The backend port is no longer exposed to the host.
    # Nginx will access it through the internal Docker network.
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://badisjl99:123951Ba008@mongo:27017/mydb?authSource=mydb
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: badisjl99
      MONGO_INITDB_ROOT_PASSWORD: 123951Ba008
    networks:
      - app_network
    # You can expose this port if you need to connect to the DB from your local machine
    # ports:
    #   - "27017:27017"

networks:
  app_network:
    driver: bridge

volumes:
  mongo-data: