version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # do NOT publish 27017 to the Internet
    networks:
      - app-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    expose:
      - "8082"
    # optional: map host port if you want to test directly, not needed for prod behind nginx
    ports:
      - "8082:8082"
    networks:
      - app-net

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    depends_on:
      - backend
    # HTTP only at first; we'll switch to SSL after issuing the cert
    ports:
      - "80:80"
    volumes:
      # share certs + ACME challenge with certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    networks:
      - app-net

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    entrypoint: /bin/sh
    networks:
      - app-net

volumes:
  mongo-data:
  certbot-etc:
  certbot-var:

networks:
  app-net:
    driver: bridge
