version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: badisjl99
      MONGO_INITDB_ROOT_PASSWORD: 123951Ba008

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      NODE_ENV: production
      PORT: 8082
      MONGO_URI: mongodb://mongo:27017/mydb
      JWT_SECRET: BFEec8JKk:FZz3f0F812f.0051293f
      COOKIE_NAME: token

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://codatalab.cloud/api
        VITE_NODE_ENV: production
    container_name: web
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    networks:
      - app-network

volumes:
  mongo-data:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
