version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mern-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  backend:
    build:
      context: ./backend
    container_name: mern-backend
    restart: always
    environment:
      PORT: 8082
      MONGO_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/your_db_name?authSource=admin # <-- CHANGE your_db_name
      # Add any other backend environment variables here
    depends_on:
      - mongo
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
    container_name: mern-frontend
    restart: always
    networks:
      - mern-network

  nginx:
    image: nginx:stable-alpine
    container_name: mern-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - mern-network

  certbot:
    image: certbot/certbot
    container_name: mern-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local